### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by danielcompton** [yeller/yeller-timbre-appender#2]
References old version of Yeller Clojure library, possibly Timbre as well.

**Comment by tom-pang** [comment]
Hey Daniel,

Thanks for the heads up :+1: 

Fixed the old versions of Yeller deps with release `1.2.0`. I haven't bumped the timbre dep because the new `timbre` changes the appender API. Are you using timbre `4.0` ? I'll get round to it eventually, but much faster if you actually want/need timbre `4.0`.

**Comment by tom-pang** [comment]
Actually NVM. `yeller-timbre-appender` version `2.0` supports timbre `4.0`. It's not backwards compatible (as timbre `4.0` was a breaking api change), so this client isn't compatible with previous versions of timbre (but `yeller-timbre-appender` `1.2.0` is compatible with previous versions of timbre.

**Comment by danielcompton** [comment]
Great thanks! I'm using Sente which I don't think is using 4.0. BTW, you might want to update the README with version details (perhaps outlining 1.2.0 and 2.0.0?)
